### ISSUE TITLE
Call to a member function getAttribute() on null

### ISSUE THREAD

**Issue by edmasonline** [boxfrommars/rutorika-sortable#74]
Hello, i have problem

vendor/rutorika/sortable/src/Rutorika/Sortable/SortableTrait.php on line 92
My DB table position col is broken queue. I'm not sure if it affects.
![index](https://user-images.githubusercontent.com/10058912/77860415-cb5e7180-7217-11ea-9c10-d9f9dcf774b8.png)

**Comment by boxfrommars** [comment]
**About gaps**: position column is for ordering only, so gaps don't affect anything. This gaps appear if you delete some items. Because after deletion the column is not recalculated. And it's OK to have them. 

**About error**: this error is caused by the absence of a `$positionEntity`:
```php
$entity->moveAfter($positionEntity);
```
so check how you select the `$positionEntity`
